import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "material-icons/iconfont/material-icons.css";
import "../public/globals.css";
// import "./globals.css";
import Navbar from "./components/navbar";
 import AdminMenuDetail from "@/components/AdminMenu";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700"], // Add the weights you need
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${poppins.className}`}
        suppressHydrationWarning={true}
      >
        <Navbar />
        <AdminMenuDetail />
        <main className="max-w-full mx-auto">{children}</main>
      </body>
    </html>
  );
}